# Include the project-wide makefile to get 
# appropriate definitions
include $(PV_TOP)/makefile.pv



LIBDIRS = \
        oscl \
        pvlogger/build/make \
        unit_test/build/make \
	../codecs_v2/colorconvert/build/make \
        ../baselibs/pv_mime_utils/build/make \
	../pvmi/pvmf/build/make \
        ../nodes/common/build/make \
	../pvmi/media_io/pvmiofileoutput/build/make \
	../pvmi/media_io/pvomaplinuxvideofb/build/make

include $(MK)/recursive.mk
